INSERT INTO ACTORS (ID, FIRST_NAME, LAST_NAME) VALUES (1, 'Brad', 'Pitt');
INSERT INTO ACTORS (ID, FIRST_NAME, LAST_NAME) VALUES (2, 'Edward', 'Norton');

INSERT INTO MOVIES (ID, TITLE, DURATION) VALUES (1, 'Fight Club', 139);
INSERT INTO MOVIES (ID, TITLE, DURATION) VALUES (2, 'Zodiac', 157);

INSERT INTO ACTORS_MOVIES(ACTOR_ID, MOVIE_ID) VALUES (1, 1);
INSERT INTO ACTORS_MOVIES(ACTOR_ID, MOVIE_ID) VALUES (2, 1);
INSERT INTO ACTORS_MOVIES(ACTOR_ID, MOVIE_ID) VALUES (1, 2);